#!/usr/bin/env bash
# Enable Hubble Timescape Beta UI features: Network Security -> Assessment and
# Enforcement Points. These are Helm toggles (default false). Uses --reuse-values
# so existing settings are preserved; only the two flags are added.
#
# Effect: the hubble-timescape-lite pod restarts (~30-60s). ClickHouse uses an
# emptyDir so flow history resets and refills from the live stream within ~1 min.
set -euo pipefail

NS=hubble-timescape
RELEASE=hubble-timescape
CHART=isovalent/hubble-timescape
VERSION=1.18.7

echo "== helm upgrade (enable assessment + enforcement points) =="
helm -n "$NS" upgrade "$RELEASE" "$CHART" --version "$VERSION" --reuse-values \
  --set ui.networkSecurity.assessment.enabled=true \
  --set ui.networkSecurity.enforcementPoints.enabled=true

echo "== wait for rollout =="
kubectl -n "$NS" rollout status statefulset/hubble-timescape-lite --timeout=180s

echo "== verify toggles =="
kubectl -n "$NS" get cm hubble-timescape-lite-config -o yaml \
  | tr ',' '\n' | grep -E 'assessment|enforcement-points|enabled' | head

echo "Done. Assessment (Beta) + Enforcement Points (Beta) tabs are now enabled."
echo "Note: the ZeroTrust assessment report is generated by the analyzer on a 24h schedule."
