apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetragon
  namespace: monitoring
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames: ["tetragon"]
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon
  endpoints:
    - port: metrics
      interval: 15s
